### ISSUE TITLE
fail build with ffmpeg 4.0

### ISSUE THREAD

**Issue by sl1pkn07** [dwbuiten/d2vsource#35]
~~~bash
make: Entering directory '/tmp/makepkg/vapoursynth-plugin-d2vsource-git/src/build'
  CXX      src/core/compat.lo
  CXX      src/core/d2v.lo
In file included from ../d2vsource/src/core/d2v.cpp:36:
../d2vsource/src/core/d2v.hpp:71:5: error: 'FF_IDCT_XVIDMMX' was not declared in this scope
     FF_IDCT_XVIDMMX,
     ^~~~~~~~~~~~~~~
../d2vsource/src/core/d2v.hpp:71:5: note: suggested alternative: 'FF_IDCT_XVID'
     FF_IDCT_XVIDMMX,
     ^~~~~~~~~~~~~~~
     FF_IDCT_XVID
../d2vsource/src/core/d2v.cpp: In function 'd2vcontext* d2vparse(const char*, std::__cxx11::string&)':
../d2vsource/src/core/d2v.cpp:96:32: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'd2vcontext' {aka 'struct d2vcontext'} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(ret, 0, sizeof(*ret));
                                ^
In file included from ../d2vsource/src/core/d2v.cpp:36:
../d2vsource/src/core/d2v.hpp:82:16: note: 'd2vcontext' {aka 'struct d2vcontext'} declared here
 typedef struct d2vcontext {
                ^~~~~~~~~~
make: *** [Makefile:539: src/core/d2v.lo] Error 1
make: Leaving directory '/tmp/makepkg/vapoursynth-plugin-d2vsource-git/src/build'
~~~

**Comment by sl1pkn07** [comment]
this is ok?

~~~patch
diff --git a/src/core/d2v.hpp b/src/core/d2v.hpp
index f87b1a0..ecdae78 100644
--- a/src/core/d2v.hpp
+++ b/src/core/d2v.hpp
@@ -68,7 +68,7 @@ static const int idct_algo_conv[8] = {
     FF_IDCT_AUTO,
     FF_IDCT_AUTO,
     FF_IDCT_AUTO,
-    FF_IDCT_XVIDMMX,
+    FF_IDCT_XVID,
     FF_IDCT_SIMPLEMMX
 };
 
diff --git a/src/core/decode.cpp b/src/core/decode.cpp
index b563697..72006dd 100644
--- a/src/core/decode.cpp
+++ b/src/core/decode.cpp
@@ -246,7 +246,7 @@ decodecontext *decodeinit(d2vcontext *dctx, int threads, string& err)
      * Enable EMU_EDGE so that we can use buffers that are
      * not padded by 32 pixels.
      */
-    ret->avctx->flags |= CODEC_FLAG_EMU_EDGE;
+/*    ret->avctx->flags |= CODEC_FLAG_EMU_EDGE;*/
 
     /* Use refcounted frames. */
     ret->avctx->refcounted_frames = 1;
~~~

**Comment by dwbuiten** [comment]
Hi, sorry I missed this. Will merge fix today.
